remote_theme: pages-themes/hacker@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
title: My first page!
author: Ivan Sanchez
description: Github Page Lab
baseurl: /skills-github-pages

collections:
  my_collection:
    output: true
    permalink: /:collection/:name


#permalink: /:year/:month/:day/:title.html
#permalink: /:title.html/

